In [133]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [135]:
df=pd.read_csv('spam.csv')
df

      Unnamed: 0 spamORham                                            Message
0              0       ham  Go until jurong point, crazy.. Available only ...
1              1       ham                      Ok lar... Joking wif u oni...
2              2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3              3       ham  U dun say so early hor... U c already then say...
4              4       ham  Nah I don't think he goes to usf, he lives aro...
...          ...       ...                                                ...
5567        5567      spam  This is the 2nd time we have tried 2 contact u...
5568        5568       ham              Will Ì_ b going to esplanade fr home?
5569        5569       ham  Pity, * was in mood for that. So...any other s...
5570        5570       ham  The guy did some bitching but I acted like i'd...
5571        5571       ham                         Rofl. Its true to its name

[5572 rows x 3 columns]

In [137]:
cols=df.columns
cols

Index(['Unnamed: 0', 'spamORham', 'Message'], dtype='object')

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5572 non-null   int64
 1   spamORham   5572 non-null   object
 2   Message     5572 non-null   object
dtypes: int64(1), object(2)
memory usage: 130.7+ KB

In [141]:
df.isnull().sum()

Unnamed: 0    0
spamORham     0
Message       0
dtype: int64

In [143]:
print(df[cols].value_counts())

Unnamed: 0  spamORham  Message
0           ham        Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                                                          1
3712        ham        If i not meeting Ì_ all rite then i'll go home lor. If Ì_ dun feel like comin it's ok.                                                                                                                   1
3720        ham        Blank is Blank. But wat is blank? Lol                                                                                                                                                                    1
3719        ham        Yeah why not, is the gang all ready                                                                                                                                                                      1
3718        spam       Thanks for your ringtone order, reference number X49. Your mobile will be charged 4.50. Should your tone not arrive please call customer services 09065989182. From: [colour=red]text[/colour]TXTstar    1
                                                                                                                                                                                                                               ..
1855        ham        K.:)you are the only girl waiting in reception ah?                                                                                                                                                       1
1854        ham        They did't play one day last year know even though they have very good team.. Like india.                                                                                                                1
1853        ham        I just made some payments so dont have that much. Sorry. Would you want it fedex or the other way.                                                                                                       1
1852        spam       This is the 2nd time we have tried 2 contact u. U have won the 750 Pound prize. 2 claim is easy, call 08718726970 NOW! Only 10p per min. BT-national-rate                                                1
5571        ham        Rofl. Its true to its name                                                                                                                                                                               1
Name: count, Length: 5572, dtype: int64

In [145]:
col='spamORham'
scaler=LabelEncoder()
df[col]=scaler.fit_transform(df[col])

In [147]:
df

      Unnamed: 0  spamORham                                            Message
0              0          0  Go until jurong point, crazy.. Available only ...
1              1          0                      Ok lar... Joking wif u oni...
2              2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3              3          0  U dun say so early hor... U c already then say...
4              4          0  Nah I don't think he goes to usf, he lives aro...
...          ...        ...                                                ...
5567        5567          1  This is the 2nd time we have tried 2 contact u...
5568        5568          0              Will Ì_ b going to esplanade fr home?
5569        5569          0  Pity, * was in mood for that. So...any other s...
5570        5570          0  The guy did some bitching but I acted like i'd...
5571        5571          0                         Rofl. Its true to its name

[5572 rows x 3 columns]

In [149]:
X=df['Message']
y=df['spamORham']

In [151]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [153]:
tfidf = TfidfVectorizer(stop_words='english')

In [155]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [156]:
print(X_train_tfidf.shape)

(4457, 7472)

In [159]:
model=MultinomialNB()
model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [161]:
y_pred=model.predict(X_test_tfidf)

In [163]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.9668161434977578
[[965   0]
 [ 37 113]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.75      0.86       150

    accuracy                           0.97      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.97      0.96      1115